### PR TITLE
AncientBeast.com FTW!

### PR DESCRIPTION
**Pull request by DreadKnight**
Materialize and control a squad of creatures with unique stats and abilities in order to defeat your foes. Master your beasts!

Find out more about it or play for free from your browser on PC/tablet/phone from official website https://AncientBeast.com

I hope this PR gets merged in asap, because we really need more coding contributions 🛠️ 
Thanks for creating this list-repo to help out free open source game projects 🙏🏻 
Here's one of our project tokens as a reward https://www.mintme.com/token/XatteR/intro/airdrop 🐺 
Hold on to it, goal is $120 within next 3 years 🚀

### CODE REVIEW

**Comment by verbes4** [comment]
Is this a game *remake*? It has to be a remake to be on this list.

**Comment by DreadKnight** [comment]
@lolicop123 Yes, it's not meant to be 1:1 clone, but the Heroes of Might and Magic 3 fans instantly get the whole deal.
It has also been listed over here for many years now https://osgameclones.com/#heroes-of-might-and-magic-iii-games

**Comment by verbes4** [comment]
Gotcha, awesome. Thanks for the link too.

**Comment by DreadKnight** [comment]
No problem. Glad you like it. Don't forget to approve the PR :-) Thanks!

**Comment by radek-sprta** [comment]
I have to say the game looks impressive. However, I'd like to reserve this list only for open-source re-implementations, not merely ones inspired by a different game.

**Pull request closed without merging**
