### PR TITLE
Add Ancient Beast to Strategy category

### PR DESCRIPTION
**Pull request by ghost**
I added Ancient Beast to the Strategy category

### CODE REVIEW

**Comment by DreadKnight** [comment]
@tsabitahh Good job 🤞🏻

**Comment by radek-sprta** [comment]
Thank you for your contribution. This looks more like an original game inspired by HOMAM, rather than HOMAM remake. Is that right?

**Comment by ghost** [comment]
Yes

**Comment by DreadKnight** [comment]
It's a modern remake, not meant to be a 100% clone. A spiritual successor to HoMM3 basically from many points of view.

**Pull request merged**
